In [1]:
import numpy as  np
import pandas as pd
import matplotlib.pyplot as plt

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
X = np.load('X.npy')
y = np.load('y.npy')

In [3]:
X.shape

(10000, 11)

In [4]:
y.shape

(10000,)

In [5]:
X[0,:-1]

array([  0.,   0., 619.,   0.,  42.,   2.,   0.,   1.,   1.,   1.])

In [6]:
X[0,10]

101348.88

Grouping credit scores as 800 - 850, 740 - 799, 670 - 739, 580 - 669 and 300 - 579  
These groups are according to the standards used in banks

In [7]:
credit_grade = np.zeros((10000,))

In [8]:
credit_grade.shape

(10000,)

In [9]:
credit_grade[X[:,2] >= 800] = 5

vgood1 = X[:,2] >= 740
vgood2 = X[:,2] <= 799
vgood = vgood1 == vgood2

credit_grade[vgood] = 4

good1 = X[:,2] >= 670
good2 = X[:,2] <= 739
good = good1 == good2
print('are first five >= 670    ',list(good1[:5]))
print('are first five <= 739    ',list(good2[:5]),'\n')
print('first five are    ',good[:5])
credit_grade[good] = 3

ave1 = X[:,2] >= 580
ave2 = X[:,2] <= 669
ave = ave1 == ave2
credit_grade[ave] = 2

poor1 = X[:,2] >= 300
poor2 = X[:,2] <= 579
poor = poor1 == poor2
credit_grade[poor] = 1

are first five >= 670     [False, False, False, True, True]
are first five <= 739     [True, True, True, True, False] 

first five are     [False False False  True False]


In [10]:
credit_grade[:5]

array([2., 2., 1., 3., 5.])

In [11]:
X[:5,2]

array([619., 608., 502., 699., 850.])

### Inserting credit_grade in X

In [12]:
X = np.insert(X, -1, values = credit_grade, axis = 1)
X.shape

(10000, 12)

In [13]:
X[:5, 10]

array([2., 2., 1., 3., 5.])

In [14]:
X[0,:-1]

array([  0.,   0., 619.,   0.,  42.,   2.,   0.,   1.,   1.,   1.,   2.])

In [15]:
X[0,-1]

101348.88

### One-hot encoding credit_grade colomn which is colomn number 10

In [16]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [10])
X = onehotencoder.fit_transform(X).toarray()
X[0,:]

array([0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
       0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [17]:
X.shape

(10000, 16)

In [19]:
X[0,:-1]

array([  0.,   1.,   0.,   0.,   0.,   0.,   0., 619.,   0.,  42.,   2.,
         0.,   1.,   1.,   1.])

In [20]:
X[0,-1]

101348.88

### Remove the first colomn to avoid dummy variable trap

In [21]:
X = X[:,1:]

In [22]:
X.shape

(10000, 15)

### Customers with no balance are more likely to close their bank account

In [26]:
X[0,10]

0.0

In [27]:
balance = np.zeros((10000,))
balance.shape

(10000,)

In [28]:
balance[X[:,10] > 0] = 1

In [29]:
balance[:5]

array([0., 1., 1., 0., 1.])

In [30]:
X = np.insert(X, -1, values = balance, axis = 1)
X.shape

(10000, 16)

In [33]:
X[0,:-1]

array([  1.,   0.,   0.,   0.,   0.,   0., 619.,   0.,  42.,   2.,   0.,
         1.,   1.,   1.,   0.])

In [34]:
X[0,-1]

101348.88

### According to a FICO report, customers aged between 25 - 34 leave bank 3 times more  
### New feature will be: user's age is between 25 - 34 or not
### Its selection will be 

In [35]:
is_age = np.zeros((10000,))

In [36]:
X[0,8]

42.0

In [37]:
lb = X[:,8] >= 25
ub = X[:,8] <= 34
valid = lb == ub
is_age[valid] = 1

In [38]:
is_age[0]

0.0

In [40]:
is_age[7]

1.0

In [41]:
X = np.insert(X, -1, values = is_age, axis = 1)
X.shape

(10000, 17)

In [42]:
X[0,:-1]

array([  1.,   0.,   0.,   0.,   0.,   0., 619.,   0.,  42.,   2.,   0.,
         1.,   1.,   1.,   0.,   0.])

In [43]:
X[0,-1]

101348.88

### Save numpy array

In [45]:
np.save('np/fe_X.npy',X)